"use client";
import { useEffect,useMemo,useState } from "react";
import { Flame, Radio, Trophy } from "lucide-react";
import type { MatchdayHubData } from "../../lib/matchday-hub";
const KEY="huja-anonymous-device-v1";
function deviceId(){let v=localStorage.getItem(KEY);if(!v){v=crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`;localStorage.setItem(KEY,v)}return v}
function Countdown({date}:{date:string}){const [now,setNow]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);const d=Math.max(0,new Date(date).getTime()-now);const days=Math.floor(d/86400000),h=Math.floor(d/3600000)%24,m=Math.floor(d/60000)%60,s=Math.floor(d/1000)%60;return <span className="tabular-nums">{days>0?`${days}T `:""}{String(h).padStart(2,"0")}:{String(m).padStart(2,"0")}:{String(s).padStart(2,"0")}</span>}
export default function MatchdayHubClient({data}:{data:MatchdayHubData}){
 const {match}=data; const [home,setHome]=useState(1),[away,setAway]=useState(1),[name,setName]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [counts,setCounts]=useState(data.reactions);
 const phase=match.status; const total=useMemo(()=>Object.values(counts).reduce((a,b)=>a+b,0),[counts]);
 async function tip(){setBusy(true);setMessage("");const r=await fetch("/api/matchday/predict",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({matchId:match.id,deviceId:deviceId(),displayName:name,homeScore:home,awayScore:away})});const p=await r.json();setMessage(r.ok?"Dein Tipp ist gespeichert. HUJA!":p.error);setBusy(false)}
 async function react(reaction:string){const r=await fetch("/api/matchday/react",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({matchId:match.id,deviceId:deviceId(),reaction})});const p=await r.json();if(r.ok)setCounts(p.counts);else setMessage(p.error)}
 return <section className="club-section py-8"><div className="club-container"><div className="club-card overflow-hidden border-club-light-red/20">
  <div className="flex items-center justify-between gap-3 border-b border-white/10 bg-gradient-to-r from-club-burgundy/80 to-transparent px-5 py-4"><div><p className="club-eyebrow">HUJA Matchday Hub</p><h2 className="mt-1 text-xl font-black uppercase text-white">{phase==="live"?"🔴 Jetzt Live":phase==="finished"?"Abpfiff":"Der Spieltag kommt"}</h2></div>{phase==="live"?<Radio className="animate-pulse text-red-400"/>:<Flame className="text-club-light-red"/>}</div>
  <div className="p-5 sm:p-7"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><p className="font-black text-white">{match.home_team}</p><div><p className="text-4xl font-black text-white">{phase==="scheduled"?"VS":`${match.home_score??0}:${match.away_score??0}`}</p>{phase==="scheduled"&&<p className="mt-2 text-xs font-bold text-club-light-red"><Countdown date={match.match_date}/></p>}</div><p className="font-black text-white">{match.away_team}</p></div>
  {phase==="scheduled"&&<div className="mt-7 rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-sm font-black uppercase text-white">⚽ Ergebnis tippen</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Dein Fan-Name" maxLength={30} className="rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-white"/><input type="number" min="0" max="30" value={home} onChange={e=>setHome(Number(e.target.value))} className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-center text-white sm:w-20"/><span className="self-center text-center font-black">:</span><input type="number" min="0" max="30" value={away} onChange={e=>setAway(Number(e.target.value))} className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-center text-white sm:w-20"/></div><button onClick={tip} disabled={busy} className="club-button-primary mt-4">{busy?"Speichert …":"Tipp abgeben"}</button><p className="mt-3 text-xs text-zinc-500">5 Punkte exaktes Ergebnis · 2 Punkte richtige Tendenz · {data.predictionCount} Tipps</p></div>}
  {phase==="live"&&<div className="mt-7"><a href={`/match-center/${match.id}`} className="club-button-primary w-full">🔴 LiveCenter öffnen</a><div className="mt-4 rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-sm font-black uppercase text-white">Live-Reaktionen</p><div className="mt-3 flex flex-wrap gap-2">{["🔥","❤️","👏","⚽"].map(x=><button key={x} onClick={()=>react(x)} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-lg">{x} <span className="text-xs text-zinc-400">{counts[x]??0}</span></button>)}</div><p className="mt-2 text-xs text-zinc-500">{total} Reaktionen</p></div></div>}
  {phase==="finished"&&<div className="mt-7 text-center"><Trophy className="mx-auto text-club-light-red"/><p className="mt-3 font-black uppercase text-white">Spiel beendet</p><p className="mt-2 text-sm text-zinc-400">Jetzt Spieler des Spiels wählen und den Matchday abschließen.</p></div>}
  {message&&<p className="mt-4 text-sm font-bold text-club-light-red">{message}</p>}
  {data.leaderboard.length>0&&<div className="mt-7 border-t border-white/10 pt-5"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">🏆 HUJA Tipprangliste</p><div className="mt-3 space-y-2">{data.leaderboard.map((e,i)=><div key={`${e.name}-${i}`} className="flex justify-between rounded-xl bg-white/[0.04] px-3 py-2 text-sm"><span className="font-bold text-white">{i+1}. {e.name}</span><span className="font-black text-club-light-red">{e.points} Pkt.</span></div>)}</div></div>}
  </div></div></div></section>
}
