"use client";
import { useMemo, useState } from "react";
import { Beaker, Goal, Pause, Play, Redo2, RotateCcw, ShieldAlert, UsersRound, Flag, Sparkles } from "lucide-react";

type Player={id:string;first_name:string;last_name:string;shirt_number:number|null};
type Event={id:string;type:"goal"|"yellow"|"red"|"sub";minute:number;player?:string;assist?:string};
export default function TestLabSimulator({players}:{players:Player[]}){
 const [minute,setMinute]=useState(0),[phase,setPhase]=useState("Bereit"),[home,setHome]=useState(0),[away,setAway]=useState(0),[events,setEvents]=useState<Event[]>([]);
 const sorted=useMemo(()=>[...players].sort((a,b)=>a.last_name.localeCompare(b.last_name,"de")||a.first_name.localeCompare(b.first_name,"de")),[players]);
 const [scorer,setScorer]=useState(sorted[0]?.id??""),[assist,setAssist]=useState("");
 const name=(id?:string)=>sorted.find(p=>p.id===id)?`${sorted.find(p=>p.id===id)!.first_name} ${sorted.find(p=>p.id===id)!.last_name}`:"";
 function add(type:Event["type"],player=scorer,secondary=assist){setEvents(v=>[{id:crypto.randomUUID(),type,minute,player,assist:secondary},...v]);navigator.vibrate?.(18)}
 function goal(){setHome(v=>v+1);add("goal")}
 function opponent(){setAway(v=>v+1);setEvents(v=>[{id:crypto.randomUUID(),type:"goal",minute},...v])}
 function reset(){setMinute(0);setPhase("Bereit");setHome(0);setAway(0);setEvents([])}
 function scenario(kind:string){
  if(kind==="hattrick"){const p=scorer;setHome(3);setAway(0);setMinute(67);setPhase("2. Halbzeit");setEvents([12,38,67].reverse().map(m=>({id:crypto.randomUUID(),type:"goal" as const,minute:m,player:p}))}
  if(kind==="comeback"){setHome(3);setAway(2);setMinute(82);setPhase("2. Halbzeit");setEvents([{id:crypto.randomUUID(),type:"goal",minute:82,player:scorer},{id:crypto.randomUUID(),type:"goal",minute:74,player:scorer},{id:crypto.randomUUID(),type:"goal",minute:61,player:scorer},{id:crypto.randomUUID(),type:"goal",minute:49},{id:crypto.randomUUID(),type:"goal",minute:31}])}
  if(kind==="last"){setHome(2);setAway(1);setMinute(89);setPhase("2. Halbzeit");setEvents([{id:crypto.randomUUID(),type:"goal",minute:89,player:scorer},{id:crypto.randomUUID(),type:"goal",minute:53},{id:crypto.randomUUID(),type:"goal",minute:18,player:scorer}])}
 }
 const scorerGoals=events.filter(e=>e.type==="goal"&&e.player===scorer).length;
 const special=scorerGoals>=3?"🔥 HATTRICK":scorerGoals===2?"🔥 DOPPELPACK":minute>=85&&events[0]?.type==="goal"?"⏱️ LAST-MINUTE":"";
 return <div className="space-y-5">
  <div className="sticky top-20 z-30 rounded-3xl border border-amber-400/25 bg-amber-950/95 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-3"><Beaker className="text-amber-300"/><div><p className="text-sm font-black uppercase text-amber-200">Testmodus aktiv</p><p className="text-xs text-amber-400/80">Nur lokale Simulation · keine Pushs · keine Statistiken · nicht öffentlich</p></div></div></div>
  <section className="club-card overflow-hidden"><div className="p-6 text-center"><p className="club-eyebrow">HUJA Testspiel</p><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><b>Middelich-Resse</b><div><p className="text-5xl font-black">{home}<span className="mx-2 text-club-light-red">:</span>{away}</p><p className="mt-2 text-xs font-black text-club-light-red">{minute}' · {phase}</p></div><b>Testgegner</b></div>{special&&<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-950/30 p-4 text-2xl font-black text-white">{special}</div>}</div></section>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><button onClick={()=>{setPhase("1. Halbzeit");setMinute(1)}} className="club-button-primary min-h-16"><Play size={18}/>Anpfiff</button><button onClick={()=>{setPhase("Halbzeit");setMinute(45)}} className="club-button-secondary min-h-16"><Pause size={18}/>Halbzeit</button><button onClick={()=>{setPhase("2. Halbzeit");setMinute(46)}} className="club-button-secondary min-h-16"><Redo2 size={18}/>2. Halbzeit</button><button onClick={()=>{setPhase("Abpfiff");setMinute(90)}} className="club-button-secondary min-h-16"><Flag size={18}/>Abpfiff</button></section>
  <section className="club-card p-5"><p className="club-eyebrow">LiveCenter Simulation</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-black text-zinc-500">Torschütze</span><select className="admin-input" value={scorer} onChange={e=>setScorer(e.target.value)}>{sorted.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label><label><span className="mb-2 block text-xs font-black text-zinc-500">Vorlage</span><select className="admin-input" value={assist} onChange={e=>setAssist(e.target.value)}><option value="">Keine Vorlage</option>{sorted.filter(p=>p.id!==scorer).map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</select></label></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><button onClick={goal} className="club-button-primary min-h-16 flex-col"><Goal size={20}/>Tor</button><button onClick={opponent} className="club-button-secondary min-h-16 flex-col"><Goal size={20}/>Gegentor</button><button onClick={()=>add("yellow")} className="club-button-secondary min-h-16 flex-col"><ShieldAlert size={20}/>Gelb</button><button onClick={()=>add("sub")} className="club-button-secondary min-h-16 flex-col"><UsersRound size={20}/>Wechsel</button></div><div className="mt-4 flex items-center gap-3"><button onClick={()=>setMinute(v=>Math.max(0,v-1))} className="club-button-secondary">-1</button><div className="flex-1 text-center text-2xl font-black">{minute}'</div><button onClick={()=>setMinute(v=>Math.min(130,v+1))} className="club-button-secondary">+1</button></div></section>
  <section className="club-card p-5"><div className="flex items-center gap-3"><Sparkles className="text-club-light-red"/><h2 className="text-lg font-black uppercase">Schnelltests</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><button onClick={()=>scenario("hattrick")} className="club-button-secondary min-h-14">🔥 Hattrick</button><button onClick={()=>scenario("comeback")} className="club-button-secondary min-h-14">⚡ Comeback</button><button onClick={()=>scenario("last")} className="club-button-secondary min-h-14">⏱️ Last-Minute</button></div></section>
  <section className="club-card p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-black uppercase">Test-Timeline</h2><button onClick={reset} className="club-button-secondary"><RotateCcw size={16}/>Reset</button></div><div className="mt-4 space-y-2">{events.length?events.map(e=><div key={e.id} className="rounded-2xl border border-white/10 bg-black/25 p-3 text-sm"><b className="text-club-light-red">{e.minute}'</b> · {e.type==="goal"?"⚽ Tor":e.type==="yellow"?"🟨 Gelb":e.type==="red"?"🟥 Rot":"🔄 Wechsel"} {e.player&&<span>· {name(e.player)}</span>}{e.assist&&<span className="text-zinc-500"> · Vorlage {name(e.assist)}</span>}</div>):<p className="text-sm text-zinc-500">Noch keine Test-Ereignisse.</p>}</div></section>
 </div>
}
