-- HUJA v21.0.0 – Fan Experience
-- Spieler-des-Spiels-Voting + anonyme App-Analytics

create extension if not exists pgcrypto;

create table if not exists public.fan_polls (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null unique references public.matches(id) on delete cascade,
  status text not null default 'open' check (status in ('open','closed')),
  ends_at timestamptz not null,
  winner_player_id uuid references public.players(id) on delete set null,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fan_poll_candidates (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.fan_polls(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (poll_id, player_id)
);

create table if not exists public.fan_poll_votes (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.fan_polls(id) on delete cascade,
  candidate_player_id uuid not null references public.players(id) on delete cascade,
  voter_hash text not null,
  created_at timestamptz not null default now(),
  unique (poll_id, voter_hash)
);

create index if not exists fan_poll_votes_poll_idx on public.fan_poll_votes(poll_id);
create index if not exists fan_poll_votes_created_idx on public.fan_poll_votes(created_at desc);

create table if not exists public.app_analytics_sessions (
  anon_hash text primary key,
  current_path text not null default '/',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists app_analytics_sessions_last_seen_idx on public.app_analytics_sessions(last_seen_at desc);

create table if not exists public.app_analytics_events (
  id bigint generated by default as identity primary key,
  anon_hash text not null,
  event_type text not null check (event_type in ('page_view')),
  path text not null,
  created_at timestamptz not null default now()
);

create index if not exists app_analytics_events_created_idx on public.app_analytics_events(created_at desc);
create index if not exists app_analytics_events_path_idx on public.app_analytics_events(path);

alter table public.fan_polls enable row level security;
alter table public.fan_poll_candidates enable row level security;
alter table public.fan_poll_votes enable row level security;
alter table public.app_analytics_sessions enable row level security;
alter table public.app_analytics_events enable row level security;

-- Kein direkter Browserzugriff notwendig: HUJA nutzt hierfür ausschließlich
-- die eigenen Next.js-Serverrouten mit SUPABASE_SECRET_KEY/Service Role.
revoke all on public.fan_polls from anon, authenticated;
revoke all on public.fan_poll_candidates from anon, authenticated;
revoke all on public.fan_poll_votes from anon, authenticated;
revoke all on public.app_analytics_sessions from anon, authenticated;
revoke all on public.app_analytics_events from anon, authenticated;
