-- HUJA v21.1.0 – Matchday Hub
-- Anonyme Ergebnistipps + Tipprangliste + Live-Reaktionen

create table if not exists public.match_predictions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  voter_hash text not null,
  display_name text not null default 'HUJA-Fan',
  home_score integer not null check (home_score between 0 and 30),
  away_score integer not null check (away_score between 0 and 30),
  points integer not null default 0 check (points in (0,2,5)),
  is_exact boolean not null default false,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(match_id, voter_hash)
);
create index if not exists match_predictions_match_idx on public.match_predictions(match_id);
create index if not exists match_predictions_points_idx on public.match_predictions(points desc);

create table if not exists public.match_reactions (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  voter_hash text not null,
  reaction text not null check (reaction in ('🔥','❤️','👏','⚽')),
  created_at timestamptz not null default now(),
  unique(match_id, voter_hash, reaction)
);
create index if not exists match_reactions_match_idx on public.match_reactions(match_id);

alter table public.match_predictions enable row level security;
alter table public.match_reactions enable row level security;
revoke all on public.match_predictions from anon, authenticated;
revoke all on public.match_reactions from anon, authenticated;
-- Zugriff ausschließlich über HUJA Next.js Serverrouten / Service Role.
